// Attendance configuration
export const ATTENDANCE_CONFIG = {
  DEFAULT_DURATION_MINUTES: 10,
  TOKEN_ROTATION_SECONDS: 10,
  MAX_DURATION_MINUTES: 30,
  MIN_DURATION_MINUTES: 5,
  LATE_THRESHOLD_MINUTES: 5,
}
